=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP1/tp_4_dtd.dtd
<!ELEMENT cv (etatcivil,formation+,experience*)>
<!ELEMENT etatcivil (nom,prenom,age,lieu)>
<!ELEMENT formation (titre,date,mention?,description?)>
<!ELEMENT experience (libelle,fonction?,annee,observation?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT libelle (#PCDATA)>
<!ELEMENT mention (#PCDATA)>
<!ELEMENT fonction (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT observation (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP1/tp_4.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE cv SYSTEM "tp_4_dtd.dtd">
<cv>
  <etatcivil>
    <nom>Lecheheb</nom>
    <prenom>Djaafar</prenom>
    <age>20</age>
    <lieu>Ouargla</lieu>
  </etatcivil >
  <formation>
    <titre>Hello world</titre>
    <date>2023</date>
    <!-- <mention>text</mention> 
  <description>text</description>  -->
  </formation >
  <experience>
    <libelle>text</libelle>
    <!-- <fonction>text</fonction> -->
    <annee>text</annee>
    <!-- <observation>text</observation> -->
  </experience >

</cv>
