=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo7_dtd.dtd
<!ELEMENT math (mrow)>
<!ELEMENT mrow (msup,(mo|mn)+)>
<!ELEMENT msup (mi,mn)>
<!ELEMENT mo (#PCDATA)>
<!ELEMENT mn (#PCDATA)>
<!ELEMENT mi (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo7.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="Tp2_exo7_xsd.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>

<!DOCTYPE math SYSTEM "Tp2_exo7_dtd.dtd">
<math> 
  <mrow> 
  <msup>
    <mi>x</mi> 
    <mn>2</mn> 
  </msup> 
  <mo>+</mo>
  <mn>4</mn>
  <mo>=</mo> 
  <mn>0</mn> 
  </mrow> 
</math> 
<!-- x^2 + 4 = 0 -->
<!-- x = 2 -->
