=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo6_dtd.dtd
<!ELEMENT table_personne (personne+)>
<!ELEMENT personne (nom,phone,email)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table_personne SYSTEM "Tp2_exo6_dtd.dtd">
<table_personne>
  <personne>
    <nom>alan</nom>
    <phone>3127786</phone>
    <email>alan@abc.com</email>
  </personne>
  <personne>
    <nom>sara</nom>
    <phone>2136877</phone>
    <email>sara@xyz.edu</email>
  </personne>
  <personne>
    <nom>fred</nom>
    <phone>7786312</phone>
    <email>fd@ac.uk</email>
  </personne>
</table_personne>
