=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo5_dtd.dtd
<!ELEMENT courses (course+)>
<!ELEMENT course (gagnant,second?,les_arbitres?,debut?,fin?)>
<!ATTLIST course numero CDATA #REQUIRED>
<!ELEMENT gagnant (#PCDATA)>
<!ATTLIST gagnant temps CDATA #IMPLIED>
<!ELEMENT second (#PCDATA)>
<!ELEMENT les_arbitres (arbitre1,arbitre2)>
<!ELEMENT arbitre1 (#PCDATA)>
<!ATTLIST arbitre1 nom CDATA #REQUIRED>
<!ELEMENT arbitre2 (#PCDATA)>
<!ATTLIST arbitre2 nom CDATA #REQUIRED>
<!ELEMENT debut (#PCDATA)>
<!ATTLIST debut format_heure CDATA #REQUIRED>
<!ELEMENT fin (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP2/Tp2_exo5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE courses SYSTEM "Tp2_exo5_dtd.dtd">
<courses>
  <course numero="c8">
    <gagnant temps="35">Dupont</gagnant>
    <second>Durand</second>
    <les_arbitres>
      <arbitre1 nom='TMartinT'/>
      <arbitre2 nom='TLegrandT'/>
    </les_arbitres>
    <debut format_heure="hh:mm"> 13:00 </debut>
    <fin> 13:53 </fin>
  </course>
  <course numero="c9">
    <gagnant>
      Rameau
    </gagnant>
  </course>
</courses>
