=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/Tp3_exo_4_dtd.dtd
<!ELEMENT inscriptions (ue+,etudiant*)>
<!ELEMENT ue (titre,resume,inscrit*)>
<!ATTLIST ue code CDATA #REQUIRED>
<!ATTLIST ue niveau CDATA #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT inscrit EMPTY>
<!ATTLIST inscrit num CDATA #REQUIRED>
<!ATTLIST inscrit semestre CDATA #REQUIRED>
<!ELEMENT etudiant (nom,adresse)>
<!ATTLIST etudiant num CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/Tp3_exo_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="Tp3_exo_4_xsd.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE inscriptions SYSTEM "Tp3_exo_4_dtd.dtd">
<inscriptions>
  <ue code="123" niveau="L3">
    <titre>djaafar</titre>
    <resume>cdnkscds</resume>
    <inscrit num="132" semestre="semestre 5" />
  </ue>
  <etudiant num="123">
    <nom>djaafar</nom>
    <adresse>ourgla</adresse>
  </etudiant>
</inscriptions>
