=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/Tp3_exo_2_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT personne (nom,prenom,dateNaissance,ville,sexe,enfants)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT dateNaissance (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT sexe (#PCDATA)>
<!ELEMENT enfants (nom_complet+)>
<!ELEMENT nom_complet (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/Tp3_exo_2_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="Tp3_exo_2_xsd.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE personne SYSTEM "Tp3_exo_2_dtd.dtd">
<personne>
  <nom>djaafar</nom>
  <prenom>lecheheb</prenom>
  <dateNaissance>2002-09-19</dateNaissance>
  <ville>Ourgla</ville>
  <sexe>homme</sexe>
  <enfants>
    <nom_complet>Lecheheb Aziz</nom_complet>
    <nom_complet>Lecheheb Aymen</nom_complet>
  </enfants>
</personne>
