=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/intiro_G3A/intiro_G3A_dtd.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT catalogue (cinema,film)>
<!ELEMENT cinema (nom,adresse,seance)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (ville,lieu)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT seance EMPTY>
<!ATTLIST seance heure CDATA #REQUIRED
ref_film CDATA #REQUIRED>
<!ELEMENT film (titre,annee)>
<!ATTLIST film film_id ID #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT annee (#PCDATA)>

=== LechehebDjaafar/TP_DSS_L3/TP_Dss/TP3/intiro_G3A/intiro_G3A.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="intiro_G3A_xsd.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE catalogue SYSTEM "intiro_G3A_dtd.dtd">
<catalogue>
    <cinema>
        <nom>UGC</nom>
        <adresse>
            <ville>Rouen</ville>
            <lieu>Salnt Sever</lieu>
        </adresse>
        <seance heure="20h" ref_film="id_GM" />
    </cinema>
    <film film_id="id_GM">
        <titre>La Graine et le mutet</titre>
        <annee>2007</annee>
    </film>
</catalogue>
